Person/Man/Woman
YashchicheC/Lessons pull request #11
Opened 2022-06-07 10:55 UTC by YashchicheC

1) Create a parent class Person
2) Create two children classes Man and Woman.class
3) Create Main class for launching and tests
4) Variables firstName, lastName, age, partner in the Person
5) Methods and constructor in the class Person
6) Overrides this methods in children

2022-06-07 10:58 UTC, Singh212dab requested changes

2022-06-07 10:58 UTC, Singh212dab commented on Lesson_16_Inheritance/src/main/java/Person.java
> +        lastName = newSurname;
this.lastName = newSurname;

2022-06-10 21:49 UTC, taraskarpenko requested changes

2022-06-10 21:49 UTC, taraskarpenko commented on Lesson_16_Inheritance/src/main/java/Person.java
> +   protected boolean partner;
Так как партнер это тоже человек, было б логичнее если б тип был Person, и соответственно регистрируя и дерегистрируя брак это поле устанавливалось у обеих партнеров. Тоесть если Маша жена Пети, то Пета муж Маши, и не может стать мужем Кати

2022-06-10 21:49 UTC, taraskarpenko commented on Lesson_16_Inheritance/src/main/java/Person.java
> +      if (ageOfPerson > 60)
Задача была в том что у мужчины и женщины разный пенсионный возраст. 
Тут можно вместо 60 вызвать метод getRetirementAge() который в этом классе сделать абстрактным, и определить его в классе мужчины и женщины так что б они возвращали разное значение

2022-06-10 21:49 UTC, taraskarpenko commented on Lesson_16_Inheritance/src/main/java/Woman.java
> +    Person person = new Person("White","Winehouse", 70, true);
Вы фактически применили композицию там где нужно наследование, так как Women является Person

2022-06-10 21:49 UTC, taraskarpenko commented on Lesson_16_Inheritance/src/main/java/Woman.java
> +    public void setAge(int age) {
Геттеры и сеттеры переопределять нет надобности

2022-06-13 07:26 UTC, YashchicheC commented on Lesson_16_Inheritance/src/main/java/Person.java
> +        lastName = newSurname;
done

2022-06-13 08:31 UTC, YashchicheC commented on Lesson_16_Inheritance/src/main/java/Person.java
> +   protected boolean partner;
done

2022-06-13 08:32 UTC, YashchicheC commented on Lesson_16_Inheritance/src/main/java/Woman.java
> +    Person person = new Person("White","Winehouse", 70, true);
изменено в связи с добавлением экземпляра Person вместо boolean

2022-06-13 08:34 UTC, YashchicheC commented on Lesson_16_Inheritance/src/main/java/Woman.java
> +    public void setAge(int age) {
удалено

2022-06-13 08:35 UTC, YashchicheC commented on Lesson_16_Inheritance/src/main/java/Person.java
> +      if (ageOfPerson > 60)
getRetirementAge() нет в условии к домашнему заданию.
Реализация выполнена через переопределение значения максимального возраста для каждого из классов

2022-06-13 12:54 UTC, merged