Lesson 6
YashchicheC/Lessons pull request #4
Opened 2022-02-15 12:40 UTC by YashchicheC

Homework (Lesson_6)
Каждое из подзаданий выводил на отдельной строке

2022-02-15 15:11 UTC, taraskarpenko requested changes

2022-02-15 15:11 UTC, taraskarpenko commented on Lesson_6/src/main/java/Main.java
> +        System.out.println("result1+1 = " + (result1 + 1));
в данном случае в консоль будет выведено 5, но состояние result1 останется 4
надо либо 
`System.out.println("result1+1 = " + (result1 += 1));` - оператор += фактически увеличивает result1 и потом возвращает новое значение

либо
```
result1 += 1;
System.out.println("result1+1 = " + (result1));
```
еще вариант
```
System.out.println("result1+1 = " + ++result1);
```
как видите, в последнем варианте преинкремент сливается визуально с оператором +, поэтому тут форматирование строк будет предпочтительнее

```
System.out.printf("result1+1 = %s \n", ++result1);
```

2022-02-15 15:11 UTC, taraskarpenko commented on Lesson_6/src/main/java/Main.java
> +        System.out.println("result1 or result2 are multiple of 2 = " + (result1%2 ==0 || result2%2 ==0));
Из-за того что предыдущие манипуляции +1 и +2 не привели к изменению состояния переменных result1 и result2 происходит проверка некорректных значений

2022-02-16 05:34 UTC, YashchicheC commented
правки в коммите "[вынесение отдельно переприсваивания значения](https://github.com/YashchicheC/Lessons/commit/64f7fa619a4a8e86e0f037d5424eb9213a12073e)"

2022-02-16 08:55 UTC, taraskarpenko commented on Lesson_6/src/main/java/Main.java
> +        result2 = result2 - 2;
Это не является ошибкой, гл более распространенная форма
`result2 -= 2;`

2022-02-16 08:55 UTC, taraskarpenko approved these changes

2022-02-16 10:54 UTC, closed without merging